package rules;

import com.example.demo.model.LoginEvent
import com.example.demo.model.EnumTimePeriod
import com.example.demo.service.DimensionService
global DimensionService dimensionService

rule "98_login_ip"
    salience 98
    lock-on-active true
    when
        event:LoginEvent()
    then
        int count  = dimensionService.distinctCount(event,new String[]{LoginEvent.OPERATEIP},EnumTimePeriod.LASTHOUR,LoginEvent.MOBILE);
        if(event.addScore(count,5,2,1)){
            dimensionService.insertRiskEvent(event,"近1小时内同ip出现多个mobile,count="+count);
        }


        count = dimensionService.count(event,new String[]{LoginEvent.OPERATEIP},EnumTimePeriod.LASTMIN);
                 if(event.addScore(count,20,10,1)){
                      dimensionService.insertRiskEvent(event,"近1分钟同ip登陆频次,count="+count);
                 }

        //同一设备登陆不同账号次数限制

end